version: "3.4"
services:
  php:
    build:
      context: .
      target : web_app_php
    restart: always
    volumes:
      - ./:/var/www/html/
    ports:
      - "80:80"
  db:
    build:
      context: .
      target: web_app_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: antadis
    ports:
      - "30306:3306"